### PR TITLE
Implement feature for health check

### PR DESCRIPTION
**Pull request by utilForever**
This revision includes:
- Implement feature for health check
  - Implement a basic health-check endpoint
  - Implement integration test for a health-check endpoint

### CODE REVIEW

**Review by w8385 — DISMISSED** [review]
헬스체크 엔드포인트 확인했습니다

**Review by plzfday — DISMISSED** [review]
It looks good! It may be obvious, but it'd be nice to see some explanations of the test's behaviour in the comment.

**Comment by utilForever** [comment]
> It looks good! It may be obvious, but it'd be nice to see some explanations of the test's behaviour in the comment.

I agree. I renamed the function to be more meaningful. Please check again.

**Review by plzfday — APPROVED** [review]
LGTM!

**Review by w8385 — APPROVED** [review]
LGTM :>

**Pull request merged**
